export const TEXT_REDUCER_ACTION_TYPES = {
    GET_TEXT: "TEXT: GET_TEXT",
    GET_TEXT_SUCCEED: "TEXT: GET_TEXT_SUCCEED",
};

export const LOADING_STATE_REDUCER_ACTION_TYPES = {
    LOADING_STATE: "CHANGE: LOADING_STATE",
};

export const TYPING_REDUCER_ACTION_TYPES = {
    POST_TYPING: "TYPING: POST_TYPING",
    POST_TYPING_SUCCEED: "TYPING: POST_TYPING_SUCCEED",
};

export const INITIALISE_TYPING_REDUCER_ACTION_TYPES = {
    INITIALISE_STORE: "STORE: INITIALISE_STORE",
    INITIALISE_RESULTS:"STORE: INITIALISE_RESULTS"
};
