export const USERS_REDUCER_ACTION_TYPES = {
    GET_USERS: "USERS: GET_USERS",
    GET_USERS_SUCCEED: "USERS: GET_USERS_SUCCEED",
    LOADING_STATE: "CHANGE: LOADING_STATE"
};

export const CERTAIN_USER_REDUCER_ACTION_TYPES = {
    GET_CERTAIN_USER: "CERTAIN_USER: GET_CERTAIN_USER",
    GET_CERTAIN_USER_SUCCEED: "CERTAIN_USER: GET_CERTAIN_USER_SUCCEED",
    POST_CERTAIN_USER: "CERTAIN_USER: POST_CERTAIN_USER",
    POST_CERTAIN_USER_SUCCEED: "CERTAIN_USER: POST_CERTAIN_USER_SUCCEED",
};

export const INITIALISE_USERS_REDUCER_ACTION_TYPES = {
    INITIALISE_STORE: "STORE: INITIALISE_STORE"
};


